source("global_env_methods/binance_api.R")
library(httr)
library(stringr)
library(jsonlite)
orderbook <- binanceOrderBook(symbol = "BTCUSDT", limit = 5000, parsed = T)
write.csv(x = orderbook$asks, file = paste0("BTC-", str_remove_all(as.character(Sys.Date()), "[:punct:]"), "-asks.csv"), sep = ",", append = F, col.names = T)
write.csv(x = orderbook$bids, file = paste0("BTC-", str_remove_all(as.character(Sys.Date()), "[:punct:]"), "-bids.csv"), sep = ",", append = F, col.names = T)
orderbook <- binanceOrderBook(symbol = "LENDUSDT", limit = 5000, parsed = T)
write.csv(x = orderbook$asks, file = paste0("LEND-", str_remove_all(as.character(Sys.Date()), "[:punct:]"), "-asks.csv"), sep = ",", append = F, col.names = T)
write.csv(x = orderbook$asks, file = paste0("LEND-", str_remove_all(as.character(Sys.Date()), "[:punct:]"), "-bids.csv"), sep = ",", append = F, col.names = T)

trades <- binanceRecentTradedList(symbol = "BTCUSDT", limit = 1000, parsed = T)
write.csv(x = trades, file = paste0("BTC-", str_remove_all(as.character(Sys.Date()), "[:punct:]"), "-trades.csv"), sep = ",", append = F, col.names = T)
trades <- binanceRecentTradedList(symbol = "LENDUSDT", limit = 1000, parsed = T)
write.csv(x = trades, file = paste0("LEND-", str_remove_all(as.character(Sys.Date()), "[:punct:]"), "-trades.csv"), sep = ",", append = F, col.names = T)

list_price_btc <- binanceSymbolPriceTricker(symbol = "BTCUSDT", parsed = T)
list_price_lend <- binanceSymbolPriceTricker(symbol = "LENDUSDT", parsed = T)
write.csv(x = data.frame("BTC" = list_price_btc$price, "LEND" = list_price_lend$price))